version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORK_VOLUME_MOUNT_PATH: /home/jovyan/work
    env_file: .env
    command:
      [
        "start.sh",
        "jupyter",
        "lab",
        "--LabApp.token=${JUPYTER_PASSWORD}",
        "--NotebookApp.notebook_dir=/home/jovyan",
        "--ContentsManager.allow_hidden=true"
      ]
    ports:
      - "${JUPYTER_EXPOSED_PORT}:8888"
    volumes:
      - work-volume:/home/jovyan/work

volumes:
  work-volume:


